current_year: 2025
random_seed: 42

preprocessing:
  test_size: 0.2
  random_state: 42
  feature_selection:
    method: "rfecv"
    cv_folds: 5
    scoring: "r2"

training:
  model_type: "Linear_regression"

evaluation:
  cross_validation:
    enabled: true
    cv_folds: 5
    scoring: "r2"
